name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t raja1111/web2-client:latest --build-arg VITE_APP_NODE_ENV='production' --build-arg VITE_APP_SERVER_BASE_URL='${{secrets.VITE_APP_SERVER_BASE_URL}}' ./frontend

      - name: Publish Image to Docker Hub
        run: docker push raja1111/web2-client:latest
        
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull raja1111/web2-client:latest

      - name: Delete old container
        run: docker rm -f new-web2-client-container   

      - name: Run Docker Container
        run: docker run -d -p 5173:80 --name new-web2-client-container raja1111/web2-client:latest
